# Site wide configuration

title: Labhacker
description: "Adventures in Data Sitting"
logo: 120x120.gif # 120x120 px default image used for Twitter summary card
teaser: 400x250.gif # 400x250 px default teaser image used in image archive grid
locale: en
url: http://labhacker.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Andrew Bauman
  email:
  twitter:
  google:
    ad-client:
    ad-slot:
  bio: A data artisan
  avatar: bio-photo_active_160.jpg # 160x160 px image for author byline
  disqus-shortname: labhacker


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
